implicit utf8 encoding on html read/write
Otherwise for some reason on Python 3.6 (Conda) io.read defaults to
cp1252 causing an exception:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position
41217: character maps to <undefined>